version: '3.9'
services:
  app:
    container_name: spring-boot-app
    build: .
    image: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/
  postgres:
    container_name: spring-boot-postgres
    image: postgres:15.1-alpine3.16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: